export const PLATFORM_TENANT_ID = 'platform';

export const COLLECTIONS = {
  tenants: 'tenants',
  users: 'users',
  memberships: 'memberships',
  students: 'students',
  subscriptions: 'subscriptions',
  plans: 'plans',
  countryPricing: 'country_pricing',
  attendance: 'attendance',
  timetables: 'timetables',
  homework: 'homework',
  notices: 'notices',
  results: 'results',
  fees: 'fees',
  feedPosts: 'feed_posts',
  events: 'events',
  galleries: 'galleries',
  busRoutes: 'bus_routes',
  busLocations: 'bus_locations',
  onlineClasses: 'online_classes',
  notifications: 'notifications',
  aiSessions: 'ai_sessions',
  otpSessions: 'otp_sessions',
  paymentIntents: 'payment_intents',
  webhookEvents: 'webhook_events',
  featureFlags: 'feature_flags',
  branches: 'branches',
  classes: 'classes',
  sections: 'sections',
  subjects: 'subjects',
  auditLogs: 'audit_logs',
} as const;

export const GRADE_NUMERIC: Record<string, number> = {
  nursery: 0,
  lkg: 0,
  ukg: 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '8': 8,
  '9': 9,
  '10': 10,
  '11': 11,
  '12': 12,
};

export const SUPPORTED_CURRENCIES = [
  'USD',
  'EUR',
  'GBP',
  'INR',
  'AED',
  'SGD',
  'AUD',
  'CAD',
] as const;

export const COUNTRY_PAYMENT_PROVIDER: Record<string, 'stripe' | 'razorpay'> = {
  IN: 'razorpay',
  US: 'stripe',
  GB: 'stripe',
  AE: 'stripe',
  SG: 'stripe',
  AU: 'stripe',
  CA: 'stripe',
  EU: 'stripe',
};
